spring.application.name=bytebox-backend
# ===============================
# = DATABASE CONFIGURATION
# ===============================

spring.datasource.url=jdbc:postgresql://localhost:${DB_PORT}/${DB_NAME}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver


# ===============================
# = JPA / HIBERNATE CONFIG
# ===============================

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect


# ===============================
# = SERVER CONFIG
# ===============================

server.port=8080


# ===============================
# = OPTIONAL (Better Logging)
# ===============================

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# ===============================
# = JUDGE0 CONFIG
# ===============================

judge0.api.url=https://judge0-ce.p.rapidapi.com/submissions?base64_encoded=false&wait=true
judge0.api.key=${JUDGE0_API_KEY}
judge0.api.host=judge0-ce.p.rapidapi.com

