spring.application.name=bytebox-backend
# ===============================
# = DATABASE CONFIGURATION
# ===============================

# LOCAL DB CONNECTION
# spring.datasource.url=jdbc:postgresql://localhost:${DB_PORT}/${DB_NAME}
# spring.datasource.username=${DB_USER}
# spring.datasource.password=${DB_PASS}

# REMOTE DB CONNECTION
spring.datasource.url=jdbc:postgresql:${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver


# ===============================
# = JPA / HIBERNATE CONFIG
# ===============================

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect


# ===============================
# = SERVER CONFIG
# ===============================

server.port=8080


# ===============================
# = OPTIONAL (Better Logging)
# ===============================

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# ===============================
# = JUDGE0 CONFIG
# ===============================

# judge0.api.url=https://judge0-ce.p.rapidapi.com/submissions?base64_encoded=true&wait=true
# judge0.api.key=${JUDGE0_API_KEY}
# judge0.api.host=judge0-ce.p.rapidapi.com


app.frontend.url=${APP_FRONTEND_URL:http://localhost:5173}

# ===============================
# = MAIL CONFIGURATION
# ===============================

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${USER_MAIL}
spring.mail.password=${USER_MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# ===============================
# = GOOGLE OAUTH CONFIG
# ===============================

google.client.id=${GOOGLE_CLIENT_ID}

# ===============================
# = CLOUDINARY CONFIG
# ===============================

cloudinary.cloud_name=${CLOUDINARY_CLOUD_NAME}
cloudinary.api_key=${CLOUDINARY_API_KEY}
cloudinary.api_secret=${CLOUDINARY_API_SECRET}

spring.servlet.multipart.max-file-size=2MB
spring.servlet.multipart.max-request-size=2MB

